@Identity.Api_HostAddress = https://localhost:5003

POST {{Identity.Api_HostAddress}}/token
Content-Type: application/json

{
    "userId": "509DF464-4115-4008-AC19-AAD059B7ED56",
    "email": "example@test.com",
    "customClaims": {
        "admin": true,
        "trustedMember": true
    } 
}

###
